/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author snayd
 */

public class Login extends javax.swing.JFrame {
  
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        barrita.setVisible(false);
 
    }
    
    public final static int TWO_SECOND = 10;
    int contador;
    private Timer tiempo;
    
    class TimerListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent e) {
            contador++;
            if(contador == 500)
            {
                inicio();
            }
        }
    }
    
    
    void iniciosesion()
    {
        //declaracion de variable String
        String usuario,clave;
        
        usuario = txtusuario.getText();
        clave = String.valueOf(txtcontraseña.getPassword());
        
        if(usuario.equalsIgnoreCase("snayder") && clave.compareTo("123456")==0)
        {
            cargar();
        }else
        {
            JOptionPane.showMessageDialog(null,"Acceso Incorrecto");
            barrita.setVisible(false);
        }  
    }

    void cargar()
    {
        contador = -1;
        tiempo = new Timer(TWO_SECOND, new TimerListener());
        activar();
    }
    
    void activar()
    {
        tiempo.start();
    }
    
    private void inicio()
    {
        Inicio a = new Inicio();
        a.setVisible(true);
        dispose();
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        barrita = new com.icm.components.metro.ProgressBarHorizontalMetroICM();
        labelRoundMetroICM1 = new com.icm.components.metro.LabelRoundMetroICM();
        btnAceptar = new com.icm.components.metro.ButtonMetroICM();
        txtcontraseña = new com.icm.components.metro.PasswordFieldMetroICM();
        linkcontraseña = new com.icm.components.metro.LinkMetroICM();
        labelMetroICM3 = new com.icm.components.metro.LabelMetroICM();
        labelMetroICM1 = new com.icm.components.metro.LabelMetroICM();
        jLabel1 = new javax.swing.JLabel();
        txtusuario = new com.icm.components.metro.TextFieldMetroICM();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicion de sesión");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setForeground(new java.awt.Color(236, 238, 226));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barrita.setColorProgressBar(new java.awt.Color(51, 255, 0));
        barrita.setEnabled(false);
        jPanel2.add(barrita, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        labelRoundMetroICM1.setText("labelRoundMetroICM1");
        jPanel2.add(labelRoundMetroICM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 180, 170));

        btnAceptar.setText("Acepar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        txtcontraseña.setText("oulikghfgbdf");
        txtcontraseña.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcontraseñaMouseClicked(evt);
            }
        });
        jPanel2.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 216, 40));

        linkcontraseña.setText("olvide la contraseña");
        linkcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkcontraseñaMouseClicked(evt);
            }
        });
        jPanel2.add(linkcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, -1, -1));

        labelMetroICM3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMetroICM3.setText("Usuario : ");
        labelMetroICM3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(labelMetroICM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 137, 40));

        labelMetroICM1.setText("Contraseña :");
        labelMetroICM1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(labelMetroICM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 137, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\snayd\\Downloads\\login.jpg")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 560));

        txtusuario.setText("Ingrese su usuario");
        txtusuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusuarioMouseClicked(evt);
            }
        });
        jPanel2.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 988, 562));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linkcontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkcontraseñaMouseClicked
        // TODO add your handling code here:
        Reestablecer_clave a = new Reestablecer_clave();
        a.setVisible(true);
        
    }//GEN-LAST:event_linkcontraseñaMouseClicked

    private void txtcontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontraseñaMouseClicked
        // TODO add your handling code here:
        txtcontraseña.setText(null);
    }//GEN-LAST:event_txtcontraseñaMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // TODO add your handling code here:
       barrita.setVisible(true);
       iniciosesion();
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void txtusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusuarioMouseClicked
        // TODO add your handling code here:
       txtusuario.setText(null);
    }//GEN-LAST:event_txtusuarioMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new Login().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.icm.components.metro.ProgressBarHorizontalMetroICM barrita;
    private com.icm.components.metro.ButtonMetroICM btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private com.icm.components.metro.LabelMetroICM labelMetroICM1;
    private com.icm.components.metro.LabelMetroICM labelMetroICM3;
    private com.icm.components.metro.LabelRoundMetroICM labelRoundMetroICM1;
    private com.icm.components.metro.LinkMetroICM linkcontraseña;
    private com.icm.components.metro.PasswordFieldMetroICM txtcontraseña;
    private com.icm.components.metro.TextFieldMetroICM txtusuario;
    // End of variables declaration//GEN-END:variables
}
